# https://fedoraproject.org/wiki/Packaging:Haskell

%global ghc_without_dynamic 1
%global ghc_without_shared 1
%global without_prof 1
%global without_haddock 1

%global pkg_name yi

%bcond_with tests

# no useful debuginfo for Haskell packages without C sources
%global debug_package %{nil}

Name:           %{pkg_name}
Version:        0.10.1
Release:        1%{?dist}
Summary:        The Haskell-Scriptable Editor

License:        GPL+
Url:            https://hackage.haskell.org/package/%{name}
Source0:        https://hackage.haskell.org/package/%{name}-%{version}/%{name}-%{version}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
BuildRequires:  chrpath
BuildRequires:  ghc-QuickCheck-devel
BuildRequires:  ghc-array-devel
BuildRequires:  ghc-binary-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-cautious-file-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-data-default-devel
BuildRequires:  ghc-derive-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-dlist-devel
#BuildRequires:  ghc-dynamic-state-devel
#BuildRequires:  ghc-dyre-devel
BuildRequires:  ghc-filepath-devel
#-BuildRequires:  ghc-fingertree-devel
BuildRequires:  ghc-hashable-devel
BuildRequires:  ghc-hint-devel
#BuildRequires:  ghc-lens-devel
#BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-old-locale-devel
#BuildRequires:  ghc-oo-prototypes-devel
BuildRequires:  ghc-parsec-devel
#BuildRequires:  ghc-pointedlist-devel
BuildRequires:  ghc-process-devel
BuildRequires:  ghc-random-devel
BuildRequires:  ghc-regex-base-devel
BuildRequires:  ghc-regex-tdfa-devel
BuildRequires:  ghc-safe-devel
BuildRequires:  ghc-semigroups-devel
BuildRequires:  ghc-split-devel
BuildRequires:  ghc-tagged-devel
BuildRequires:  ghc-template-haskell-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-transformers-base-devel
BuildRequires:  ghc-uniplate-devel
BuildRequires:  ghc-unix-compat-devel
BuildRequires:  ghc-unix-devel
BuildRequires:  ghc-unordered-containers-devel
BuildRequires:  ghc-utf8-string-devel
#BuildRequires:  ghc-vty-devel
#BuildRequires:  ghc-word-trie-devel
BuildRequires:  ghc-xdg-basedir-devel
#BuildRequires:  ghc-yi-language-devel
#BuildRequires:  ghc-yi-rope-devel
ExclusiveArch:  %{ghc_arches_with_ghci}
%if %{with tests}
BuildRequires:  ghc-HUnit-devel
BuildRequires:  ghc-tasty-devel
BuildRequires:  ghc-tasty-hunit-devel
BuildRequires:  ghc-tasty-quickcheck-devel
%endif
# End cabal-rpm deps
BuildRequires:  cabal-dev
BuildRequires:  ghc-zlib-devel
BuildRequires:  ghc-terminfo-devel

%description
Yi is a text editor written in Haskell and extensible in Haskell. The goal of
the Yi project is to provide a flexible, powerful, and correct editor for
haskell hacking.


%prep
%setup -q


%build
[ -d "$HOME/.cabal" ] || cabal update
#%%global cabal cabal-dev -s %{_builddir}/cabal-dev
%global cabal cabal-dev
%cabal install-deps
cabal_configure_extra_options="--ghc-option=-O1"
%ghc_bin_build


%install
%ghc_bin_install

rm -r %{buildroot}%{ghclibdir}


%check
%if %{with tests}
%cabal test
%endif


%files
%doc LICENSE
%doc example-configs
%{_bindir}/%{name}
%{_datadir}/%{name}-%{version}


%changelog
* Thu Oct 23 2014 Jens Petersen <petersen@redhat.com> - 0.10.1-1
- update to 0.10.1

* Thu Oct  2 2014 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 0.8.2-1
- spec file generated by cabal-rpm-0.9.1.50
- cabal-dev'ified

